version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_user_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sample_db
    ports:
      - "13306:3306"

  web:
    build: .
    command: /bin/bash
    environment:
      EDITOR: "emacs"
    volumes:
      - .:/sample_app
    ports:
      - "3000:3000"
    links:
      - db
    tty: true
