version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: sample_password
      MYSQL_DATABASE: sample_database
    ports:
      - "3005:3005"

  web:
    build: .
    command: /bin/bash
    environment:
      EDITOR: "emacs"
    volumes:
      - .:/sample_app
    ports:
      - "3000:3000"
    links:
      - db
    tty: true
